#!/usr/bin/env python

def latexify(
        texequation,
        outfname = None,
        verbose = False,
        density = 300):

    import subprocess
    import tempfile
    import os

    head = r"""% latex file create by sandbox.py
    \documentclass{standalone}
    \begin{document}
    $\displaystyle
    """

    foot = r"""
    $
    \end{document}
    """

    # create temporary files/directories
    tmpdir = tempfile.mkdtemp()
    tmptexfname = os.path.join(tmpdir,"texeq.tex")
    tmpoutfname = os.path.join(tmpdir,"texeq.pdf")

    # write the tmp texfile
    with open(tmptexfname,'w') as f:
        f.write(head)
        f.write(texequation)
        f.write(foot)

    # compile the tex file in tmpdir
    stdout = None if verbose else open(os.devnull,'w')
    popen = subprocess.Popen("pdflatex -interaction=nonstopmode -pdf %s"%tmptexfname,
                shell=True,cwd=tmpdir,stdout=stdout,stderr=stdout)
    popen.wait()
    if not verbose: stdout.close()

    # exit if not compiled
    if popen.returncode != 0:
        print "Compilation failed. Run again with -v to detect errors in your formula."
        exit()

    # create output
    if not outfname:
        with open(tmpoutfname,'r') as f:
            print f.read()
    else:
        _,ext = os.path.splitext(outfname)
        if ext == '.pdf':
            subprocess.check_call("cp %s %s"%(tmpoutfname,outfname),shell=True)
        elif ext in ['.png','.jpg','.bmp']:
            subprocess.check_call("convert -density %d %s %s"%(density,tmpoutfname,outfname),shell=True)


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('texequation')
    parser.add_argument('-v','--verbose',action='count', help='print compilation output of pdflatex')
    parser.add_argument('-o','--output',help='the output file which will be generated')
    parser.add_argument('-d','--density',default=300,type=int,help='density for convert (300 is nice)')
    args = parser.parse_args()

    latexify(
            args.texequation,
            outfname=args.output,
            verbose=args.verbose,
            density=args.density)
